# config
logo: /blog/img/html.png
keywords: "front end, dev, developer, CSS, Development, Software, Web"
pubkey:
menu:
  Home: /blog
  Portfolio: /
  Articles: /blog/articles
  Contact: /blog/contact

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics: UA-72252440-1
