# config
logo: /blog/img/html.png
keywords: "front end, dev, developer, CSS, Development, Software, Web"
pubkey:
menu:
  Home: /blog
  Articles: /blog/articles
  About: /blog/about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
