# config
logo: /blog/img/html.png
keywords: "front end, dev, developer"
pubkey: 13DB CAA1 2633 81A7
menu:
  Home: /blog
  Articles: /blog/articles
  About: /blog/about

# Content
excerpt_link: Read more

# Miscellaneous
rss: /atom.xml
google_analytics:
